# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:


jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Tell a Joke Action
        uses: ArnabSau/my-github-action@v.1.3
